### PR TITLE
Added fix for wrong rdf:type to @type conversion

### LINKED ISSUE #242: rdf:type with other fields and framing produces wrong output
This is a simplified version of the problem I'm facing.

Having the following json `A`:

```json
{
  "@context": {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  },
  "@id": "http://example.com/main/id",
  "rdf:type": {
    "@id": "http://example.com/rdf/id",
    "rdf:label": "someLabel"
  }
}
```

And the following framing `B`:
```json
{
  "@context" : {
    "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  },
  "@id" : "http://example.com/main/id"
}
```

And here is the code I am using to make the apply the framing (it is in Scala, but the conversion to Java should be Trivial).

```scala
   // the original Json (A) converted to a Jena Model
   val jsonModel: Model = ???
   // the context of the original Json (A)
   val contextJson: String = ???
   // the framing (B)
   val frame: String = ???

    val g   = DatasetFactory.wrap(jsonModel).asDatasetGraph
    val out = new ByteArrayOutputStream()
    val w   = RDFDataMgr.createDatasetWriter(RDFFormat.JSONLD_FRAME_FLAT)
    val pm  = RiotLib.prefixMap(g)
    val ctx = new JsonLDWriteContext()
    ctx.setJsonLDContext(contextJson)
    ctx.setFrame(frame)
    Try {
      w.write(out, g, pm, null, ctx)
    }.flatMap(_ => parse(out.toString).toTry)
```

The output generated is wrong:
```json
{
  "@context" : {
    "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  },
  "@graph" : [
    {
      "@id" : "http://example.com/main/id",
      "@type" : "http://example.com/rdf/id"
    }
  ]
}
```
...because it is omitting the `label`. I'm expecting the output to be as the input. That's also the behaviour in the [Json-LD Playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2Fmain%2Fid%22%2C%22rdf%3Atype%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.com%2Frdf%2Fid%22%2C%22rdf%3Alabel%22%3A%22someLabel%22%7D%7D&frame=%7B%22%40context%22%3A%7B%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2Fmain%2Fid%22%7D).

More weirdly, when using a different predicate than `rdf:type`, the output is correct. So I guess is something related to the special way `rdf:type` (@type) is being treated when framing.

### PR DESCRIPTION
**Pull request by umbreak**
Fixes #242

As described on the issue, from the following triples
```
<http://example.com/Subj1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Type> .
<http://example.com/Type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#label> "myLabel" .
```
the following json should be created (event when useRdfType = false):
```json
{
   "@id": "http://example.com/Subj1",
   "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#label": "myLabel"
   }
}
```

### CODE REVIEW

File: core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java [hunk 1]
```diff
@@ -1968,48 +1977,61 @@ public boolean isWellFormedListNode() {
             }
 
             // 3.5)
+            final Map<String, List<Node>> nodes = new HashMap<>();
+
             for (final RDFDataset.Quad triple : graph) {
                 final String subject = triple.getSubject().getValue();
                 final String predicate = triple.getPredicate().getValue();
                 final RDFDataset.Node object = triple.getObject();
+                final List<Node> list = nodes.getOrDefault(subject, new ArrayList());
```
Comment (ansell) [inline core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java]: Can this like be switched from ``getOrDefault(subject, new ArrayList())`` to ``computeIfAbsent(subject, ArrayList::new)`` (or similar)? The call to ``nodes.put(subject, list)`` below is then redundant because unlike ``getOrDefault``, ``computeIfAbsent`` modifies the map if necessary before returning.

File: core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java [hunk 2]
```diff
@@ -1968,48 +1977,61 @@ public boolean isWellFormedListNode() {
...
+            for (final Map.Entry<String, List<Node>> nodeEntry : nodes.entrySet()) {
+              final String subject = nodeEntry.getKey();
+
+                for (final Node n : nodeEntry.getValue()) {
+                    final String predicate = n.predicate;
+                    final RDFDataset.Node object = n.object;
+
+                    // 3.5.1+3.5.2)
+                    NodeMapNode node;
+                    if (!nodeMap.containsKey(subject)) {
```
Comment (ansell) [inline core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java]: This can also be switched to use ``computeIfAbsent`` to remove the if statement and reduce it to a single line (I know this is previous code, but would be good to fix it now that we are relying on Java-8, which wasn't the case originally)

**Comment by ansell** [comment]
Thanks, I optimised a few other cases of get/put/get to use computeIfAbsent also and merged it in.
